class MQTTMatcher:
    class Node:
        def __init__(self) -> None: ...
    def __init__(self) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def __delitem__(self, key) -> None: ...
    def iter_match(self, topic): ...
