from .. import mqtt as mqtt
from typing import List, Tuple, Union

def multiple(msgs: Union[List[dict], List[Tuple[str, str, int, bool]]], hostname: str = ..., port: int = ..., client_id: str = ..., keepalive: int = ..., will: dict = ..., auth: dict = ..., tls: dict = ..., protocol=..., transport: str = ..., proxy_args: dict = ...) -> None: ...
def single(topic: str, payload: str = ..., qos: int = ..., retain: bool = ..., hostname: str = ..., port: int = ..., client_id: str = ..., keepalive: int = ..., will: dict = ..., auth: dict = ..., tls: dict = ..., protocol: int = ..., transport: str = ..., proxy_args: dict = ...) -> None: ...
