from _typeshed import Incomplete

class MQTTException(Exception): ...

class SubscribeOptions:
    RETAIN_SEND_ON_SUBSCRIBE: Incomplete
    RETAIN_SEND_IF_NEW_SUB: Incomplete
    RETAIN_DO_NOT_SEND: Incomplete
    QoS: Incomplete
    noLocal: Incomplete
    retainAsPublished: Incomplete
    retainHandling: Incomplete
    def __init__(self, qos: int = ..., noLocal: bool = ..., retainAsPublished: bool = ..., retainHandling=...) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def pack(self): ...
    def unpack(self, buffer): ...
    def json(self): ...
